name: Auto Update Portfolio Data

on:
  schedule:
    # 매일 오전 9시 (한국시간 오후 6시)에 실행
    - cron: '0 9 * * *'
  workflow_dispatch: # 수동 실행도 가능

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-portfolio:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Python dependencies
      run: |
        pip install requests
        
    - name: Run project scanner
      run: |
        cd ${{ github.workspace }}
        # 여기서는 실제 프로젝트 폴더가 없으므로 스킵
        # python project_scanner_fixed.py
        echo "Skipping scanner - no access to local projects"
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: update-portfolio
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
